# Generated by Django 4.2.2 on 2023-06-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='img',
            field=models.ImageField(default='gfgfg', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
